eureka:
    client:
        service-url:
            defaultZone: http://localhost:8100/eureka/
    instance:
        instance-id: ${spring.application.name}
server:
    port: 8002

spring:
    application:
        name: server_video

    jpa:
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


    datasource:
        url: jdbc:mysql://localhost:3306/server_video
        username: root
        password: deng05
        driver-class-name: com.mysql.cj.jdbc.Driver


#security:
#    oauth2:
#        resource:
#            user-info-uri: http://localhost:9098/users/current
#        client:
#            id: ${spring.application.name}
#            client-secret: 123456
#            access-token-uri: http://localhost:9098/oauth/token
#            grant-type: client_credentials,password
#            scope: server