eureka:
    client:
        service-url:
            defaultZone: http://localhost:8100/eureka/
    instance:
        instance-id: ${spring.application.name}
server:
    port: 8002

spring:
    application:
        name: server_video

#security:
#    oauth2:
#        resource:
#            user-info-uri: http://localhost:9098/users/current
#        client:
#            id: ${spring.application.name}
#            client-secret: 123456
#            access-token-uri: http://localhost:9098/oauth/token
#            grant-type: client_credentials,password
#            scope: server